Makefile.am

Without this patch I'm ending up with $(DESTDIR) twice, which doesn't feel right.
```
/usr/bin/mkdir -p '/builddir/build/BUILDROOT/rpki-client-0.3.0-2.fc33.x86_64/builddir/build/BUILDROOT/rpki-client-0.3.0-2.fc33.x86_64/etc/pki/tals'
/usr/bin/install -p -m 644 afrinic.tal apnic.tal lacnic.tal ripe.tal '/builddir/build/BUILDROOT/rpki-client-0.3.0-2.fc33.x86_64/builddir/build/BUILDROOT/rpki-client-0.3.0-2.fc33.x86_64/etc/pki/tals'
```

Avoid double $(DESTDIR) during 'make install'

---

Makefile.am

Fedora builds/installs are always unprivileged and the final permissions are handled by some RPM "magic", thus without this patch I'm ending up with the following errors and no created directories.
```
/usr/bin/install: invalid user 'rpki-client'
make[3]: [Makefile:873: install-data-hook] Error 1 (ignored)
/usr/bin/install: invalid user 'rpki-client'
make[3]: [Makefile:874: install-data-hook] Error 1 (ignored)
```
Let me know if the patch needs to be improved or rewritten.

Allow unprivileged 'make install' to succeed

---

update.sh

This small hack ensures that `git <action>` in `update.sh` only happens if `openbsd/.git` exists. It should not have any impact on regular operations, however it allows to build reproducible snapshots (if there is no release tarball) in offline build environments by filling the `openbsd` directory with a pre-defined checkout (rather depending on an internet connection for `autogen.sh` and maybe changing commits in the upstream VCS).

Limit 'git <action>' to 'openbsd/.git' existence

---

configure.ac

Three new --with flags:
--with-openssl=pkg-name Use pkg-config(1) pkg-name to find OpenSSL files
--with-openssl-cflags=STRING
Extra compiler flags to build with OpenSSL
--with-openssl-ldflags=STRING
Extra flags for linker to link with OpenSSL
libraries
Please check it out and see if that suites the needs. The cflags and ldflags will overwrite the --with-openssl cflags and ldflags (maybe we should just extend them instead.
In some cases (e.g. with the openssl package on openbsd) one needs to pass
`-Wl,-R/usr/local/lib/eopenssl11` to LDFLAGS in one way or another. Which would be easier if --with-openssl=eopenssl11 --with-openssl-ldflags=-Wl,-R/usr/local/lib/eopenssl11 would work.

Do a better job at detecting and selecting which openssl library should be used

---

configure.ac

With https://github.com/rpki-client/rpki-client-openbsd/commit/fbc33757884fada818c04cd542123c809f867a52 the dependency to `fts_open()` was introduced which is not part of musl libc (Alpine Linux), but in a separate `libfts.so`. Without this patch, the build-time failure looks like this:
```
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: rpki_client-main.o: in function `repo_cleanup':
/tmp/rpki-client-portable/src/main.c:1307: undefined reference to `fts_open'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/rpki-client-portable/src/main.c:1311: undefined reference to `fts_read'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: …
```

Link against -lfts if needed (when using musl libc)

---

patches/0003-Emit-all-formats.patch

On non-OpenBSD systems we can't assume OpenBGPD is the most useful format, so we should emit all formats by default this makes life simpler for operators: whatever your goal is running 'sudo rpki-client' will emit a useful format.

Emit all formats on non-OpenBSD platforms

---

.travis.yml

This runs rpki-client -v at the end of the travis CI build to verify that the resulting binary works (this assumes that rpki-client only exits 0 if no error happened). As usual ARIN is not tested but that's their fault.
This increases the build time by 4 minutes.
Should we add something like this?
It would be possible to run it against a small repo (exclude ripe.tal and apnic.tal) or build our own test repo that way the output could be validated as well.

Add a run of rpki-client in our CI build to see if the build works

---

compat/a_time_tm.c

The bugfix is not relevant for rpki-client, but let's try to keep this
copy in sync.

Sync a_time_tm.c with OpenBSD CVS

---

INSTALL

Adding textual assistance to how to build on MacOS. As it's mostly involving exporting the proper CPPFLAGS and LDFLAGS, I've written it down with the special CFLAGS and LDFLAGS hints.

Adding MacOS build instruction, tested succesfully on Catalina.

---

README.md

* Alpine 3.13 has been released a while ago (and rpki-client works there)
* Fedora 31 is EOL, Fedora 34 has been released recently (and rpki-client works there)
* CentOS becomes upstream of RHEL and Rocky got a downstream of RHEL (and rpki-client works on all of them)

Update working operating systems

---

INSTALL
README.md

* There is no EPEL for Fedora, just for CentOS/RHEL/Rocky
* Fedora prefers `dnf` over `yum` meanwhile (it's just a symlink)
* Our Docker/Quay containers are already built using Alpine 3.15
* RHEL 9 is around the corner (and EPEL 9 builds are working fine)
* Fedora 33 is EOL, Fedora 36 is around the corner, 37 is next

Update working Linux distributions

---

INSTALL

`X509_up_ref()` appeared for the first time with OpenSSL 1.1.0-pre1, and `ASN1_STRING_get0_data()` appeared for the first time with OpenSSL 1.1.0a.
See also:
- https://github.com/openssl/openssl/commit/05f0fb9f6acc34c82a082d7668572828925694e7
- https://github.com/openssl/openssl/commit/17ebf85abda18c3875b1ba6670fe7b393bc1f297
- https://github.com/rpki-client/rpki-client-portable/pull/7#issuecomment-615986414

Document correct minimum OpenSSL version

---

.github/workflows/codeql-analysis.yaml

LGTM.com will be shut down in December 2022 and recommend to use GitHub code scanning instead.
See also: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Add CodeQL analysis

---

configure.ac

the configure script checks for fts functions and if found, adds the -lfts to the generated makefiles but `fts.h` is directly included without any guards and the rest of the code does use `fts_*` functions, rendering the test useless.
in systems like musl hosts where an external fts implementation needs to be brought in, this causes the following error:
```c
repo.c:28:10: fatal error: 'fts.h' file not found
#include <fts.h>
```
on musl hosts the error can be prevented by building and linking against [musl-fts](https://github.com/void-linux/musl-fts) but the configure script should die if fts.h is not present during the configuration stage in order to prevent surprises:
```sh
checking for fts.h... no
configure: error: fts.h is required
```

check for fts.h availability

---

compat/Makefile.am
compat/x509_get0_uids.c
configure.ac
include/openssl/x509.h

LibreSSL < 3.7.2 doesn't support this. This allows us to use this function for a correctness check OpenBSD without needing to bump the minimum LibreSSL requirement.

Add compat shim for X509_get0_uids()

---

src/Makefile.am
update.sh

This will build after the next sync from OpenBSD.

Update build harness for log.c removal

---

configure.ac

The use the same minherit(MAP_INHERIT_ZERO) method for detection. So adjust the arc4random detection.

Since FreeBSD 12 the arc4random issues should be resolved.

---

compat/ppoll.c

Use volatile sigatomic_t for the signal handler variable and make sure the signal mask is reset back in all cases.

Fixup the ppoll compat implementation.

---

configure.ac

Same fix as I committed to openbgpd-portable. NetBSD has to be a special snowflake.

Add -D_OPENBSD_SOURCE to netbsd compile flags to handle strtonum.

---

scripts/config.guess
scripts/config.sub

Update `scripts/config.{guess,sub}` to HEAD (aka 2024-01-01) as suggested in the comments of the files (raised with https://github.com/rpki-client/rpki-client-portable/pull/111#issuecomment-2154914048 and https://github.com/openbgpd-portable/openbgpd-portable/pull/78#issuecomment-2178896336) to basically match https://github.com/openbgpd-portable/openbgpd-portable/pull/78 for consistency. But…feel free to reject this pull request if you dislike it.
Edit: CI failure results from #114, not from this PR.

Update scripts/config.{guess,sub} to HEAD (aka 2024-01-01)

---

.github/workflows/codeql-analysis.yaml

See also: https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/

Update to CodeQL Action v3

---

.github/workflows/build.yaml

It makes more sense to test building using a more than less recent compiler. Unfortunately, Ubuntu 24.04 LTS doesn't provide GCC 15 (yet?).

Switch gcc-12 to gcc-14, default is gcc-13

---

configure.ac

The first two were stolen from libressl-portable but they aren't good enough to link portable against pthread on OpenBSD since those are now in libc. pthread_join is good enough for OpenBSD, not sure if we need more here for other OS.

Add basic -lpthread detection
